# 1.	Decion regarding elective major surgery with risk :If the note contains (1) a surgery/procedure mention AND (2) planning/counseling indicators
# AND (3 or 4: either risk factors OR explicit risk discussion) → classify as High Risk (MDM Level 3, Rule 4).
Surgery_list_1 = [
    "Abdominal hysterectomy",
    "Cataract extraction",
    "Cholecystectomy",
    # "Coronary artery bypass graft (CABG)",
    "Cystoscopy",
    "Haemorrhoidectomy",
    "Hysteroscopy",
    "Inguinal herniorrhaphy",
    "Myringoplasty",
    "Tympanoplasty",
    "Myringotomy",
    "Prostatectomy",
    "Septoplasty",
    "Tonsillectomy",
    "Total hip replacement",
    "Total knee replacement",
    "Varicose veins stripping and ligation",
    "Colonoscopy",
    "EGD (Esophagogastroduodenoscopy)",
    "Carpal tunnel release",
    "Endoscopies",
    "Laparotomy",
    "Amputation",
    "Valve replacement",
    "Transplant",
    "Revascularization",
    "Joint replacement",
    "Resection",
    "Bypass surgery",
]
Surgery_discussion_list_2 = []
Risk_factors_list_3 = [
    # "CHF",
    # "CAD",
    # "atrial fibrillation",
    # "counseled extensively",
    # "AKI",
    # "renal failure",
    # "Sepsis",
    # "necrotic tissue",
    # "rapidly progressing infection",
    # "PE risk",
    # "Pulmonory Embolism",
    # "Severe COPD",
    # "Severe with exacerbation",
    "oxygen dependent 6 litre by cannula",
    "Stroke risk",
    # "neurological damage",
    # "Advanced age",
    "frailty",
    "immunosuppressed",
    # "CKD",
    "Transfusion",
    "Respiratory rate <22",
    # Newly added items
    "refusing transfusion",
    "Transfusion  order / given",
    "Arterial Line",
    "BiPap or High flow oxygen mask (nonrebreather or > 40% venti mask), Vapotherm, or AVAPS (average volume assured pressure support)",
    "Bronchoscopy (Emergent)",
    "Cardiopulmonary Resuscitation (CPR) (Time before and/or after CPR)",
    "Cath Lab - patient taken to Cath lab on current DOS",
    "Central line placement (not for inability to gain peripheral access only)",
    "Cricothyrotomy",
    "ECMO (extracorporeal membrane oxygenation)",
    "EKOS Catheter",
    "Electrical cardioversion or defibrillation",
    # "Impella",
    "Intra-aortic balloon pump (IABP)",
    "Intraosseous (IO) infusion",
    "Intubation",
    "Need for patient to go immediately to surgery for immediate stabilization or exploration of a potentially life threatening condition",
    "Left Ventricular Assist Device (LVAD)",
    "Mechanical Ventilation (excludes patients on chronic vent mgmt with improved clinical presentation)",
    "Pacemaker insertion or external pacing",
    "Pericardiocentesis",
    "Thoracentesis/Needle Decompression",
    "Thoracotomy (Initial)",
    "Thoracostomy tube/Pig tail catheter (Chest tube)  (Initial insertion)",
    "Pacemaker insertion or external pacing",
    "Mechanical Ventilation / Mechanical Ventilater",
    "Bolus of 2 liters OR 30 mL/kg IV fluids ( NS, LR, Plasma)",
    "Heart Rate (HR) > 100",
    "troponin (troponin >0.04)",
    "Anion gap 12-19",
    "on dialysis",
    "the underlying cause of encephalopathy",
    "Respiratory acidosis ) with elevated CO2",
    "Patient with cirrhosis with bleeding or infection",
    "Dialysis - Need for emergent dialysis",
    "Acute STEMI or NSTEMI taken to the cath lab",
    "Mental status not stabilized or worsening",
    "Lumbar Puncture",
    "severe lethargy.",
    "total parenteral nutrition (TPN)",
    "Need for thrombolytics (Activase, Retavase, Streptokinase, TNKase, tPA)",
    "Mechanical Ventilation or chronic Ventilation management",
    "WBC count > 12K or < 4K"
]
Risk_phrases_4 = []


EMERGENCY_MAJOR_SURGERY = [
    "Trauma injuries",
    "Acute Appendicitis",
    "Cholecystitis / Gallbladder infections",
    "Skin infections / soft tissue infections",
    "Gastrointestinal bleeding",
    "Peptic ulcer complications",
    "Acute Pancreatitis",
    "Diverticulitis and complications",
    "Ulcerative colitis",
    "Crohn's disease and complications",
    "Bowel obstruction",
    "Bleeding peptic ulcer",
    "Perforated peptic ulcer",
    "Incarcerated Hernia",
    "Strangulated Inguinal Hernia",
    "Intestinal obstruction",
    "Tube thoracostomy",
    "Blood transfusion",
    "Fluid replacement",
    "Internal bleeding control",
    "Pelvic peritonitis",
    "Colostomy",
    "Cricothyroidostomy",
    "Damage-control laparotomy",
    "Bleeding from esophageal varices",
    "Liver abscess",
    "Respiratory obstruction",
    "Surgical infections",
    "Open fracture repair",
    "ORIF",
    "Angioplasty",
    "Chest tube placement"
]

Sdoh_phrases = [
    "financial constraints",
    "lack of insurance",
    "uninsured",
    "underinsured",
    "housing instability",
    "unstable housing",
    "homeless",
    "lack of refrigeration",
    "transportation barrier",
    "lack of transportation",
    "no access to care",
    "rural access",
    "food insecurity",
    "unable to afford food",
    "language barrier",
    "low health literacy",
    "limited caregiver support",
    "social isolation",
    "treatment options limited due to",
    "diagnosis complicated by",
    "barrier to treatment",
    "prevented from accessing care",
    "engaged social work",
    "community services contacted",
    "telehealth follow-up arranged",
    "housing support",
    "transportation services",
]

Elective_major_surgery_without_risk = [
    "Abdominal hysterectomy",
    "Cataract extraction",
    "Cholecystectomy",
    # "Cystoscopy",
    "Haemorrhoidectomy",
    "Hysteroscopy",
    "Inguinal herniorrhaphy",
    "Myringoplasty",
    "Tympanoplasty",
    "Myringotomy",
    "Prostatectomy",
    "Septoplasty",
    "Tonsillectomy",
    "Total hip replacement",
    "Total knee replacement",
    "Varicose veins stripping and ligation",
    # "Colonoscopy",
    # "EGD",
    # "Carpal tunnel release",
    # "Endoscopies",
]
DNR_Hospitalization = [
    "DO NOT RESUSCITATE",
    "ADVANCE CARE DIRECTIVE - DNR",
    "ADMITTED TO THE OPERATING ROOM",
    "TRANSFER TO ANOTHER FACILITY",
    "TRANSFER TO CLEARFBRK",
    "TRANSFER TO THR",
    "DO NOT RESUSCITATE",
    " DNR ",
    " DNR.",
    ".DNR ",
    ".DNR.",
    "ADMITTED TO THE OPERATING ROOM",
    "PATIENT DNR/DNI",
    "PATIENT IS DNR",
    "ICU SERVICE NEEDED",
    "TRANSFERRED TO ICU",
    "DO NOT RESUSCITATE",
    "PATIENT IS ON DNR STATUS",
    "DNR DNI",
    "IP PSYCH PLACEMENT",
    "SEVERE ANEMIA REQUIRING PBC TRANSFUSION",
    "CONTINUE ICU CARE",
    "TRANSFUSE 1 UNIT PRBC",
    "TRANSFER TO ICU",
    "Code status: DNR",
    "Code status:DNR" "Hospitalization required",
    "Do-Not-Resuscitate",
    "Do-Not-Resuscitate (DNR)",
    "Do-Not-Resuscitate(DNR)",
]  
# HOSPITALIZATION,HOSPITALIZATION,"ADMIT TO THE HOSPITAL", "ADMITTED TO THE HOSPITAL", "ADMIT TO HOSPITAL" "ADMIT TO THE HOSPITAL",
Therapy_list_low = [
    "PHYSICAL THERAPY",
    "OCCUPATIONAL THERAPY",
    "PHISOTHERAPY",
    "SUBACROMIAL CORTISONE INJECTION",
    "HUMIDIFIER",
    "SUPPORTIVE CARE",
    "CRYOTHERAPY",
    "TOPICAL BRUSH",
    "WOULD RECOMMEND REFRAINING",
    "REFERRAL TO DERMATOLOGY OFFICE",
    "REFERRING THE PATIENT TO CARDIOLOGY",
    "THERAPEUTIC INJECTIONS",
    "RECOMMEND SURGERY",
    "BILATERAL IRRIGATION",
    "RETURN FOR A SHAVE EXCISION",
    # "RECOMMEND EXAM UNDER ANESTHESIA",
    "ESOPHAGEAL MANOMETRY",
    "TOPICAL TREATMENT",
    "STRAW COLORED WATERY DRAINAGE",
    "RECOMMEND LAPAROSCOPIC",
    "RECOMMEND LAPAROSCOPIC/ROBOTIC REPAIR",
    "RECOMMEND ROBOTIC REPAIR",
    "REFER TO NEPHROLOGY",
    "RECOMMEND WIDE LOCAL EXCISION",
    "REFERRAL TO: GENERAL SURGERY",
    "REFERRAL TO: DERMATOLOGY",
    "PROCEED WITH SURGERY",
    "SYSTANE EYE DROPS",
]
Mdm_minimal = [
    "REST",
    "GARGLES",
    "DRESSING",
    "SUPERFICIAL DRESSING",
    "ELASTIC BANDAGES",    
    "Foreign body removal",
]
